{{- if not .Values.cleaner.skip }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prepare-kubernetes-cluster.fullname" . }}
  labels:
    {{- include "prepare-kubernetes-cluster.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prepare-kubernetes-cluster.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "prepare-kubernetes-cluster.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}