{{ $cmds := list "set -x" }}

{{ range $x := .Values.node.features }}
  {{ if eq $x "DISABLE_THP" }}
    {{ $cmds = append $cmds "echo never | tee /host/sys/kernel/mm/transparent_hugepage/enabled > /dev/null" }}
  {{ end }}
{{ end }}

{{ range $x := .Values.node.sysctls }}
  {{ $cmds = append $cmds (printf "sysctl -w %v %v" $x.name $x.value) }}
{{ end }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prepare-kubernetes-cluster.fullname" . }}
  labels:
    {{- include "prepare-kubernetes-cluster.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prepare-kubernetes-cluster.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: preparer
          securityContext:
            {{- toYaml .Values.bash.securityContext | nindent 12 }}
          image: "{{ .Values.bash.repository }}:{{ .Values.bash.tag }}"
          imagePullPolicy: {{ .Values.bash.pullPolicy }}
          command:
            - sh
            - -c
            - {{ join ";" $cmds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: host-root
              mountPath: /host
      containers:
        - name: cleaner
          securityContext:
            {{- toYaml .Values.helm.securityContext | nindent 12 }}
          image: "{{ .Values.helm.repository }}:{{ .Values.helm.tag }}"
          imagePullPolicy: {{ .Values.helm.pullPolicy }}
          command:
            - helm
            - uninstall
            - {{ .Release.Name }}
            - --namespace={{ .Release.Namespace }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: host-root
          hostPath:
            path: /
      restartPolicy: Never
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
